### ISSUE TITLE
Ansii escape codes in response

### ISSUE THREAD

**Issue by Jab2870** [tallguyjenks/BusinessCard#1]
Hi, I really like the idea and borrowed it for my own business card, however, I have put the ansii escape codes directly in the response which results in not having to pipe it into sh. I haven't bothered with a url shortener but you can see it working here with:

```
curl https://jonathanh.co.uk/card.curl
```

**Comment by tallguyjenks** [comment]
yes! ive had several people remind me about the ansii codes so that it can avoid the shell pipe but ive been working with it since last night and its still not wanting to work with the ansii codes and im not sure why. either the colors dont work, or the whitespace gets messed up

**Comment by Jab2870** [comment]
The easiest way to do it would be to just pipe the output of what you have into a new file.

```
curl -sL bit.ly/2zvxUbd | sh > newFile
```

Then just put `newFile` somewhere on your webserver

**Comment by tallguyjenks** [comment]
aaaaand you just saved me so much work. thank you for this!

**Comment by Jab2870** [comment]
No problem at all.
