### ISSUE TITLE
scrot

### ISSUE THREAD

**Issue by vladdoster** [tallguyjenks/BusinessCard#4]
Only reason I changed pic is because its a bit hard to read yours. Its mostly your system and not actual biz card.

**Comment by vladdoster** [comment]
Fam, you got enough status bar blocks?. I think you need the [Double bar patch](https://dwm.suckless.org/patches/dualstatus/)

**Comment by tallguyjenks** [comment]
LOL its actually because i was on the thinkpad for the screen shot and not my monitor like i normally am lol. i've sense trimmed it down xD faire point, i'll revert that one :+1:
